# Variables:
#  - Global:
variables:
  LLVM_CONFIG: llvm-config-3.5

#  - Local:
.gcc49: &gcc49
  variables:
    CXX: "g++-4.9"
.clang35: &clang35
  variables:
    CXX: "clang++-3.5"
.debug: &debug
  variables:
    DEBUG: "1"
.release: &release
  variables:
    DEBUG: "0"

# This set of commands will run before each job.
before_script:
  - echo before
  - uname -a
  - env
  - |
    if [[ "$USE_GASNET" -eq 1 ]]; then
      export CONDUIT=mpi
      export GASNET_ROOT="$PWD/gasnet/release"
      export LAUNCHER="mpirun -n 2 -x TERRA_PATH -x INCLUDE_PATH -x LD_LIBRARY_PATH -x LG_RT_DIR"
      unset WARN_AS_ERROR
      git clone https://github.com/StanfordLegion/gasnet.git gasnet
      pushd gasnet
      make -j2
      popd
    fi

# Define Docker image to use.
.image: &image
  image: stanfordlegion/gitlab-ci # i.e. https://hub.docker.com/r/stanfordlegion/gitlab-ci/

# Define tests to run.
.tests: &tests
  script:
    - echo test
    - env
    - ./language/travis.py
    - |
      make -s -C tutorial/00_hello_world LG_RT_DIR=../../runtime clean
      make -s -C tutorial/00_hello_world LG_RT_DIR=../../runtime -j2
      tutorial/00_hello_world/hello_world -logfile out_%.log
      make -s -C tutorial/01_tasks_and_futures LG_RT_DIR=../../runtime
      tutorial/01_tasks_and_futures/tasks_and_futures -logfile out_%.log
      make -s -C tutorial/02_index_tasks LG_RT_DIR=../../runtime
      tutorial/02_index_tasks/index_tasks -logfile out_%.log
      make -s -C tutorial/03_global_vars LG_RT_DIR=../../runtime
      tutorial/03_global_vars/global_vars -logfile out_%.log
      make -s -C tutorial/04_logical_regions LG_RT_DIR=../../runtime
      tutorial/04_logical_regions/logical_regions -logfile out_%.log
      make -s -C tutorial/05_physical_regions LG_RT_DIR=../../runtime
      tutorial/05_physical_regions/physical_regions -logfile out_%.log
      make -s -C tutorial/06_privileges LG_RT_DIR=../../runtime
      tutorial/06_privileges/privileges -logfile out_%.log
      make -s -C tutorial/07_partitioning LG_RT_DIR=../../runtime
      tutorial/07_partitioning/partitioning -logfile out_%.log
      make -s -C tutorial/08_multiple_partitions LG_RT_DIR=../../runtime
      tutorial/08_multiple_partitions/multiple_partitions -logfile out_%.log
      make -s -C tutorial/09_custom_mapper LG_RT_DIR=../../runtime
      tutorial/09_custom_mapper/custom_mapper -logfile out_%.log
    - |
      make -s -C examples/full_circuit LG_RT_DIR=../../runtime
      make -s -C examples/full_circuit LG_RT_DIR=../../runtime
      examples/full_circuit/ckt_sim -logfile out_%.log
      make -s -C examples/full_ghost LG_RT_DIR=../../runtime
      examples/full_ghost/ghost -ll:cpu 4 -logfile out_%.log
    - |
      if [[ "$DEBUG" -eq 0 ]]; then
        make -s -C test/realm LG_RT_DIR=../../runtime DEBUG=0 SHARED_LOWLEVEL=0 USE_CUDA=0 USE_GASNET=0 clean
        make -s -C test/realm LG_RT_DIR=../../runtime DEBUG=0 SHARED_LOWLEVEL=0 USE_CUDA=0 USE_GASNET=0 run_all
      fi
    - |
      if [[ "$DEBUG" -eq 0 ]]; then
        make -s -C test/performance/realm LG_RT_DIR=../../../runtime SHARED_LOWLEVEL=0 clean_all
        make -s -C test/performance/realm LG_RT_DIR=../../../runtime SHARED_LOWLEVEL=0 run_all
      fi

# Define the list of jobs to run.
#  - GCC
gcc_cxx98_release:
  <<: [*gcc49, *release, *image, *tests]
  variables:
    CC_FLAGS: "-std=c++98"
gcc_cxx98_debug_checks:
  <<: [*gcc49, *debug, *image, *tests]
  variables:
    CC_FLAGS: "-std=c++98 -DPRIVILEGE_CHECKS -DBOUNDS_CHECKS"
gcc_cxx98_debug_spy:
  <<: [*gcc49, *debug, *image, *tests]
  variables:
    CC_FLAGS: "-std=c++98 -DLEGION_SPY"
    TEST_SPY: "1"
gcc_cxx11_release:
  <<: [*gcc49, *release, *image, *tests]
  variables:
    CC_FLAGS: "-std=c++11"

# - Clang
clang_cxx98_release:
  <<: [*clang35, *release, *image, *tests]
  variables:
    CC_FLAGS: "-std=c++98"
clang_cxx98_debug_checks:
  <<: [*clang35, *debug, *image, *tests]
  variables:
    CC_FLAGS: "-std=c++98 -DPRIVILEGE_CHECKS -DBOUNDS_CHECKS"
clang_cxx98_debug_spy:
  <<: [*clang35, *debug, *image, *tests]
  variables:
    CC_FLAGS: "-std=c++98 -DLEGION_SPY"
    TEST_SPY: "1"
clang_cxx11_release:
  <<: [*clang35, *release, *image, *tests]
  variables:
    CC_FLAGS: "-std=c++11"
