language: cpp
sudo: false
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
env:
  - CC_FLAGS=
  - CC_FLAGS="-DPRIVILEGE_CHECKS -DBOUNDS_CHECKS"
  - CC_FLAGS=-DLEGION_SPY
  - CC_FLAGS=-std=c++0x
matrix:
  exclude:
    - os: osx
      compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5
    packages:
      - g++-4.9
      - clang-3.5
      - libclang-3.5-dev
      - llvm-3.5-dev
before_install:
  - if [ "$(uname)" = "Linux" -a "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$(uname)" = "Linux" -a "$CXX" = "clang++" ]; then export CXX="clang++-3.5" CC="clang-3.5"; fi
  - export LLVM_CONFIG="llvm-config-3.5"
  - export TERRA_CXX="$CXX"
  - export TERRA_CC="$CC"
  - export TERRA_LINK="$CXX"
script: ./language/travis.py
